### ISSUE TITLE
ChemOffice21.0安装包无法确认条款

### ISSUE THREAD

**Issue by wehnes** [Z-H-Sun/CS_CCME_Posts#11]
安装chemoffice21.0的时候，会要求将条款下拉到底部再确认条款。但是会出现即使已经下拉到底部，确认框也是灰色无法确认的情况。多次重开安装文件也无法解决。
系统为windows10 21H2
![image](https://user-images.githubusercontent.com/14278110/171394457-6580526a-9783-49ac-b961-3e7c0d68b00d.png)

**Comment by Z-H-Sun** [comment]
Glad you found a workaround. To make it clear, this seems a problem of the original installer, so you should ask PerkinElmer not me. I will label these issues as “won’t fix” as the fix is beyond my capability.
