### ISSUE TITLE
Mestrenove更新到了14.3了，请大佬更新

### ISSUE THREAD

**Issue by deepinsc2020** [Z-H-Sun/CS_CCME_Posts#12]
Mestrenove更新到了14.3了，请大佬更新

**Comment by Z-H-Sun** [comment]
Please note: the patch applies for all versions. Just download & install MNova 14.3; then use the old patch.

Let me know should any issue come up.

**Comment by GroundStateGecko** [comment]
(Works OK on 14.3.1, Windows 10.)
