### ISSUE TITLE
The line in the NMR spectrum is strange (dotted line? incoherent?)

### ISSUE THREAD

**Issue by CielChew** [Z-H-Sun/CS_CCME_Posts#13]
Hi Sun, thank you so much for sharing Mestrenova. Actually I downloaded several versions online before this (I downloaded 14.3 from the official website and tried your patch), and I encountered a same problem in all versions, which is the line in the NMR spectrum is very strange, like a dotted line or an incoherent one (attached please see the spectrum).

I still can't figure out what's happening given that one of the version I downloaded online works well in my previous laptop (DELL insipron 14 7000, Win10), and I don't know if it's because I'm using my new laptop (Alienware x14, Win11).

Thank you for reading my issue, hope there will be a solution to this. Wish you good health and happy life!

Ciel
<img width="960" alt="Mestrenova Porblem - Ciel Chew" src="https://user-images.githubusercontent.com/117163504/199246490-4c2bfbc4-c080-43bf-a3db-c9bb164c2cf9.png">

**Comment by Z-H-Sun** [comment]
No idea what's wrong. Maybe some bug with Win11. Try playing around with the document settings, like spectrum line width, turning off grids, etc. If failed, report to MNova; unfortunately there is nothing I can help.
![12 08 15 047](https://user-images.githubusercontent.com/48094808/199281581-a7559360-6ebb-4379-a73f-a3c967bc736d.png)

**Comment by CielChew** [comment]
Thanks a lot for your help. I also tried altering the line width, though the line always looked bizarre at any width from 1.0 to 10.0. I have sent the problem to Mestrenova and I'll update here if there's any solution. By the way, have you succeeded in using Mestrenova in Win11 before? 
Actually I was asked to install NET framework 2.0 during the installation of the first version Mestrenova, and I downloaded this NET framework 2.0 after the installation finished. I wonder if this is the problem.
Thanks again.

**Comment by Z-H-Sun** [comment]
> I have sent the problem to Mestrenova and I'll update here if there's any solution.

Please do post MNova's response here.

> By the way, have you succeeded in using Mestrenova in Win11 before?

No. But others have reported problems with ChemDraw on Win11. See my general comments on Win11 here:
https://github.com/Z-H-Sun/CS_CCME_Posts/issues/9#issuecomment-1133273012

> Actually I was asked to install NET framework 2.0 during the installation of the first version Mestrenova, and I downloaded this NET framework 2.0 after the installation finished.

I think this is unlikely. dot NET framework has been designed to be cross-platform.

I might test installing MNova on Win11.

**Comment by Z-H-Sun** [comment]
> I might test installing MNova on Win11.

Looks fine on my end. Try upgrading your Win11 OS and MNova to the latest version. In document properties, click on `Restore` at the bottom left of the dialog (see previous image).


![13 40 56 334](https://user-images.githubusercontent.com/48094808/199795916-70313c00-d13c-4cc4-b2a7-63daf0330ea2.png)

**Comment by CielChew** [comment]
Thank you so much for your further information.
I just updated my Mestrenova and it still didn't work.
![image](https://user-images.githubusercontent.com/117163504/200159592-6d159b29-a9c1-4fcc-9e9c-4786ccf13e6e.png)
I'll update windows soon 
(2022-10 Cumulative Update Preview for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5018341)).
By the way, the official website just replied to me to send them a screenshot 'File/Help/License Manager' dialog box, is it okay to send them that (not sure if they've received other accounts with your licence)?

**Comment by Z-H-Sun** [comment]
> By the way, the official website just replied to me to send them a screenshot 'File/Help/License Manager' dialog box, is it okay to send them that (not sure if they've received other accounts with your licence)?

No this is not ok. The license is not authentic. Do NOT share this with MNova; otherwise you are inviting trouble. I am NOT kidding.

**Comment by CielChew** [comment]
Thank you so much again!!!
Yep.............. I assume that it's definitely not okay to send them the licence hahahah. That's why I didn't do that.
Btw, I found that after I right clicked Mestrenova , ticked "Override high DPI scaling behavior" and chose "Application" in the list, there turned to be no blank in the line on the spectrum though the DPI of the application decreased. I guess maybe the problem is caused by the incompatibility of the low DPI of Mestrenova and the high DPI (1920*1080 for 14') of the laptop?

**Comment by Z-H-Sun** [comment]
Reasonable & suprising. Reasonable because the Win11 I tested on indeed has a 100% scaling ratio, so I was unable to fully reproduce your environment. Surprising because I thought high DPI scaling should no longer be an issue in year 2022.

Anyways, really glad you've found a workaround for this mysterious issue.
