### ISSUE TITLE
Mac最新系统安装GaussView提示“gview”需要更新。

### ISSUE THREAD

**Issue by DEabcdp** [Z-H-Sun/CS_CCME_Posts#14]
macOS：13.2.1 (22D68)

双击gview后出现弹窗：“gview”需要更新。此App的开发者需要更新App以在此macOS版本上正常工作。请联系开发者了解更多信息。

<img width="776" alt="image" src="https://user-images.githubusercontent.com/62452364/219268889-45a9c822-0b62-4939-aa31-2e04488bf4df.png">

**Comment by Z-H-Sun** [comment]
Duplicate of #4
