### ISSUE TITLE
ChemDraw 22 的安装包windows提示有病毒拒绝运行

### ISSUE THREAD

**Issue by shaoqx** [Z-H-Sun/CS_CCME_Posts#16]
Windows11 安全中心提示检测到已知的风险文件 ***.h!ml (具体文件名没拷贝上)

**Comment by Z-H-Sun** [comment]
Ask PerkinElmer. They are part of the software, not from the patch, and I am not the one who developed the software. My guess is that the demo webpage for Chemscript and/or ChemDraw/Chem3D ActiveX control is the culprit. Most likely you won't need them anyway.

Just temporarily disable the Windows Smartscreen or Defender and allow the installer to run. If you are paranoid, download the official package and run [the patch](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15/COS_Win_Patch.exe) manually. And delete those suspicious files if you are super paranoid.
