### ISSUE TITLE
cos22安装时只能选择同时安装32和64位版本，能否只安装其中一个

### ISSUE THREAD

**Issue by skipskipthree** [Z-H-Sun/CS_CCME_Posts#17]
cos22crack.exe解压后安装弹框只能选择同时安装32和64为两个版本，无法手动更改。有一个解决办法是解压后，从解压文件中单独选择安装其中一个版本，然后再进行破解。这样的操作excel的插件失效。大佬能否解决一下

**Comment by skipskipthree** [comment]
两个都安装时，文件默认关联的是32位程序，再Windows默认软件设置里边设为64位为默认程序无效，仍然关联的为32位程序

**Comment by Z-H-Sun** [comment]
You surely can. In this screen, do not choose `default`, but rather `custom`. In the next screen, uncheck the 32-bit program. In doing so, you will see more dialogs popping up during the installation process, but do not panic; just click "next" all the way.

Well, if you wonder why the design for the installer is so stupid and not straightforward, ask PerkinElmer; I'm not the devoloper of the software.

![](https://user-images.githubusercontent.com/48094808/231572723-e1c82ed3-4dfa-4048-a48d-8acf46896903.png)
