### ISSUE TITLE
MRN Fedora 38

### ISSUE THREAD

**Issue by dima-huang** [Z-H-Sun/CS_CCME_Posts#19]
Hi Z.H.Sun,
I recently upgraded to **Fedora 38**, and used the patch file for MRN. It  showed this message:

79:in `<main>': undefined method `exists?' for Dir:Class (NoMethodError)

unless Dir.exists?(dir) then puts "\n\e[1;31mSeems that MRN is not installed..."; exit end
          ^^^^^^^^
Did you mean?  exist?

MRN was already installed. I got the same message with sudo privilege. In Fedora 37, it worked just fine. My ruby version is:  ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
I don't know if this is something you have time to look at, but your effort is greatly appreciated!
Thanks,
Dima

**Comment by Z-H-Sun** [comment]
The method `Dir#exists?` has been deprecated for a while and finally got removed in the latest versions of Ruby. The fix is simple: Just replace all occurrences of the `exists?` method with `exist?`.

Or, re-download and re-run the patch, where I have already incorporated the fix.
