### ISSUE TITLE
win报错

### ISSUE THREAD

**Issue by Anson-MC** [Z-H-Sun/CS_CCME_Posts#22]
应用程序无法正常启动（0xc00000tb)

**Comment by Z-H-Sun** [comment]
More information should be provided (what software, patch, operating system you are using, etc.) before I can do anything.

**Comment by Z-H-Sun** [comment]
Maybe check this out: https://ugetfix.com/ask/how-to-fix-error-code-0xc000007b-on-windows-10/

My guess is something wrong about the dependencies, e.g. VC Redist and/or .NET framework. If so, blame the software developer.

Again, not much I can help without more info. A screenshot will also be helpful.
