### ISSUE TITLE
Is it possible to block the effect of this network check?

### ISSUE THREAD

**Issue by MachineGUN001** [Z-H-Sun/CS_CCME_Posts#23]
many thanks to provide such good solutions for using Chemdraw. after using the crack patch tool to complete the installation, I still wonder whether the chemdraw could connect to the Internet, send out some info such as version license and be tracked by PerkinElmer which the cracked version is being used？Because the previous encounter was found to use the cracked version by PerkinElmer company, PE company send a lawyer warning letter. Is it possible to block the effect of this network check?

**Comment by Z-H-Sun** [comment]
My intention is to give personal users who cannot pay PerkinElmer 2 grand per year a chance to use some functions of the software, but I don't mean to break the copyright law or fight the monopoly company. This is where the line draws, so I won't actively work on what you suggest here. I'm sorry.

Nevertheless, there are several suggestions that may or may not work, and you can judge them on your own.

1. You can install the cracked software on a computer that does not have internet access. 99% of the functions in Chem Draw does not require internet access. This should work the best, but it might be an overkill.
2. Equivalently, configure your firewall such that you segregate the connection of only the targeting software (in this case, Chem Draw) to the internet.
3. Further, use some system process monitoring tool to narrow down what internet resources are the software requesting, and you can be more specific in setting the firewall rules, or you can also block these domains in the system Hosts file.
4. Maybe the company just sends out the lawyer letters at random. You might be able to get away with continuing using the cracked software, but you must take the risk of doing so.
5. If you work for a company or an academic institute, the best solution is to (politely) ask your supervisors, etc. to purchase the software or its equivalent. Come on, you are making money, and it's the minimal price you should pay to have a good set of production tools.

Disclaimer: These suggestions were given by Google searching, and they are not targeting any specific software.

Good luck.
