### ISSUE TITLE
ChemScript问题

### ISSUE THREAD

**Issue by PythonZhao** [Z-H-Sun/CS_CCME_Posts#24]
按照作者的方法,安装完windows版本 ChemOffice 22之后, 无法使用ChemScript,其他功能正常
python版本 3.9, from ChemScript22 import *  之后运行程序跳出来需要激活的窗口
![image](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/33950882/0937371a-015a-4c42-ad2a-876f21b81684)

麻烦作者看下什么原因,谢谢

**Comment by Z-H-Sun** [comment]
Possible duplicate of #15 

See [this section](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/hidden/cos/cos20.md#%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94) for more info.

**Comment by PythonZhao** [comment]
Thank you.
