### ISSUE TITLE
Anyone tried patching Mnova 15.0 yet, does it work?

### ISSUE THREAD

**Issue by HollyGolightly27** [Z-H-Sun/CS_CCME_Posts#25]

**Comment by ScienceZone** [comment]
The speed of downloading it from the official website is very slow, and it cannot be downloaded successfully, and it cannot be tested. Have you tried it, how's that?

**Comment by Z-H-Sun** [comment]
Works.

See screenshots below for both Win and Mac versions. Note the version numbers.

![win](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/48094808/f5435c71-77fb-4109-b7b2-6724290faa23)
![mac](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/48094808/8ac51963-44ae-45fd-a90d-f2d3aa09c90a)

**Comment by Z-H-Sun** [comment]
> The speed of downloading it from the official website is very slow, and it cannot be downloaded successfully, and it cannot be tested.

This is neither my problem nor MRNova's. Just another instance of China's internet access issue.

**Comment by HollyGolightly27** [comment]
That's great to hear. Thanks for testing. Have you had a chance to use any of the new features? I see in their release notes mention of AI powered peak picking... wondering if its actually any improvement, and if it constitutes me updating to 15.0. 

See new features here:
https://resources.mestrelab.com/top-features-in-mnova-15/

**Comment by Z-H-Sun** [comment]
Thank you for the notice. To be honest, I am very disappointed. No exciting updates. Confusing naming.

In the link you provided, they mention:

> Advanced Phase and Baseline Correction
> We've introduced a novel deep-learning algorithm designed to simultaneously correct phase and baseline distortions.

No, I tried the new version but didn't find anything new. There's also nothing that is relevant mentioned in their release notes. I'm not sure if they will keep it secret until future versions (then why brag about something that is not yet there???)

The only AI-related new feature added in Version 15.0.0, see [their release notes](https://resources.mestrelab.com/whats-new-in-mnova-15-0-0/):

> MLDCON peak picking has been integrated into the Method menu within the Peak Picking Options dialogue.

This is hidden very deep in the UI, and it is not set as default. And I don't feel it much different from before. And it only works for Bruker 1D 1H NMR. What's worse, it's only picking peaks, not fitting peaks (I think they especially mention they use AI to deconvolute peaks, but it's kind of weird why they hide the deconvoluted results).
