### ISSUE TITLE
cos/cos20.md的Google Drive 没有cos22.0_ 21.0_ 20.0_Crack 文件

### ISSUE THREAD

**Issue by Y0YLX-132** [Z-H-Sun/CS_CCME_Posts#26]
您好，cos/cos20.md的Google Drive 没有cos22.0_ 21.0_ 20.0_Crack 文件，可否考虑添加下。
百度网盘非会员下载限速非常严重。
![image](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/133520636/8a751ca7-6207-4c09-8c71-c61d7202ddba)

**Comment by Z-H-Sun** [comment]
The files **_are_** there, but it's just they are no longer visible to the public (see picture below). Maybe some idiots reported these files.

Please bear with the low speed of Baidu Pan for the time being, while I am thinking of workarounds. Or if you have any good idea, please let me know.

![15 30 55 558](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/48094808/d6c5918e-ebd9-44b4-a391-ef7baebae5cb)

**Comment by Y0YLX-132** [comment]
可以考虑  阿里网盘、中国移动云盘，非付费会员的下载限速相对没有百度网盘那么严重。

**Comment by Z-H-Sun** [comment]
> 可以考虑 阿里网盘、中国移动云盘，非付费会员的下载限速相对没有百度网盘那么严重。

I don't trust these companies. They will soon become the next Baidu netdisks. Like 夸克. Just disgusting.

Now, password protected RAR archives have been uploaded to [the original GDrive link](https://drive.google.com/open?id=1FT3l0msiLPsarmT78JQ8_sgbdJLMY4_X) in replacement of the public-invisible exe's. Although having to extract files twice is kind of silly, but this should to some extent bypass the censorship.

**Comment by Y0YLX-132** [comment]
非常感谢分享，你说的对，他们很快就是下一个百度网盘。
