### ISSUE TITLE
chem draw23版本破解失效

### ISSUE THREAD

**Issue by Zwd-1996** [Z-H-Sun/CS_CCME_Posts#27]
![微信截图_20240309115432](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/53620334/f78f2f94-d2e0-4cbf-bfe4-4bdd79853ac9)
您好呀，23.0版本的破解失效了，有办法可以解决吗？

**Comment by Z-H-Sun** [comment]
This issue is quite a bit more complicated than I had anticipated. For the time being, please stick to the older 22.2 version (Frankly speaking, version 23 does not come with exciting updates).

**Comment by janinsh** [comment]
是的，v23版本，好像软件的归属母公司也变了，用这个patch，我这边侦测不到软件安装情况，显示not installed。因此破解不了。还是期待能有v23的patch出来。

**Comment by Z-H-Sun** [comment]
Try the new patcher provided in the link below. I will update the articles soon.

[new.zip](https://github.com/Z-H-Sun/CS_CCME_Posts/files/14626390/new.zip)

**Comment by xaya1001** [comment]
> This issue is quite a bit more complicated than I had anticipated. For the time being, please stick to the older 22.2 version (Frankly speaking, version 23 does not come with exciting updates).

亲测官方最新版23.1，有一个非常好的功能，之前的版本都没有：

[Key highlights for ChemDraw v23.1]

![image](https://github.com/user-attachments/assets/83055022-28e7-4fe6-8969-a808db5c6c65)

能够解决下面这个帖子的问题：

[排障记录，科研绘图 Chem Draw 软件 注释没删除导致复制粘贴一次结构内存占用异常](https://s.v2ex.com/t/997220)
