### ISSUE TITLE
win 11安装的Mestrenova 15在打开软件正常，但是每次点击打他browser时就弹出如下图，重装没有解决，请问大佬遇到过这种么？怎么解决呢？

### ISSUE THREAD

**Issue by skipskipthree** [Z-H-Sun/CS_CCME_Posts#30]
![image](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/33718851/4c739056-7062-4db9-9513-c073599b4f93)

**Comment by skipskipthree** [comment]
自问自答吧，刚试了用管理员模式运行可以顺利打开data browser文件。。。尴尬了

**Comment by Z-H-Sun** [comment]
I don't see any problem on my side.
![00 01 16 142](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/48094808/fed6a535-5259-46de-9c2c-cc9d71b94909)
