### ISSUE TITLE
大佬，今天打开提示多用户使用，这个怎么破？

### ISSUE THREAD

**Issue by skipskipthree** [Z-H-Sun/CS_CCME_Posts#31]
![image](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/33718851/af94d25d-4b97-4256-a3ff-4b74cfd8ada7)

**Comment by Z-H-Sun** [comment]
Related to #5 

Prior to v23, you can use the legacy crack tool as outlined [here (Windows 下的替代破解法)](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/tags/hidden/cos/cos20.md#windows-%E4%B8%8B%E7%9A%84%E6%9B%BF%E4%BB%A3%E7%A0%B4%E8%A7%A3%E6%B3%95). This method, however, seems to no loner work for v23+

What will happen if you click on "确定"? Does this also happen to Chem 3D?

I personally have never met such situations, so it will be difficult for me to troubleshoot. I may or may not work on this known issue.

**Comment by Z-H-Sun** [comment]
Could you please try the following:

In Windows firewall settings, inbound rules, see if there are allowed rules for Chem Draw or Chem 3D. If so, for each of them, change its properties:

* `General` tab: change `Allow` to `Block` the connection
* `Advanced` tab: tick `Domain` and `Private`

If still doesn't work:

* `Protocols and Ports` tab: change Protocol type from `TCP` or `UDP` to `Any`
* Restart your PC

![00 28 06 685](https://github.com/Z-H-Sun/CS_CCME_Posts/assets/48094808/48b417ce-de6f-46c1-8b37-e31b79c9316f)

**Comment by Z-H-Sun** [comment]
This issue should be permanently solved in [the latest beta patcher](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.18rc/COS_Win_Patch.exe). Please refer to the new instructions in this section. [避免“多用户使用”警告弹窗](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/tags/hidden/cos/cos20.md#%E9%81%BF%E5%85%8D%E5%A4%9A%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8%E8%AD%A6%E5%91%8A%E5%BC%B9%E7%AA%97)

**Comment by cxd3055842561-lab** [comment]
大佬，25版的windows chemdraw补丁程序无法自动进行了。26版的补丁程序被认定为病毒自动删除，无法运行，也无法放到exclude文件夹里

<img width="1914" height="1086" alt="Image" src="https://github.com/user-attachments/assets/7861a3ac-c08c-4ecc-9d71-a7110153ce4c" />

**Comment by Z-H-Sun** [comment]
> 大佬，25版的windows chemdraw补丁程序无法自动进行了。26版的补丁程序被认定为病毒自动删除，无法运行，也无法放到exclude文件夹里
> 
> <img alt="Image" width="1914" height="1086" src="https://private-user-images.githubusercontent.com/332535515/656567676-7861a3ac-c08c-4ecc-9d71-a7110153ce4c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3OTAwOTI0MjksIm5iZiI6MTc5MDA5MjEyOSwicGF0aCI6Ii8zMzI1MzU1MTUvNjU2NTY3Njc2LTc4NjFhM2FjLWMwOGMtNGVjYy05ZDcxLWE3MTEwMTUzY2U0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDkyMlQxNTQ4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmY0Y2JlZDUwNTQxYjQ0NmU5OTgyNzU4Mzg5MDI0NGEyMzk3ZTYwODQ5MDNkM2Y0NTllODJiMzY2YjgxM2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.uJIck67Be6oGSbIRVfRY9hFfSZEdCp-Kl2pyDameR0o">

That’s not my problem. You can figure it out yourself how to deal with Windows Defender or any other antivirus software you use. In fact, read [my notes](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/tags/hidden/cos/cos26.md#%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94) on antivirus carefully: you can always [install Ruby environment](https://rubyinstaller.org/) and run the [Ruby script](https://github.com/Z-H-Sun/MRN-ADF_Patch/blob/tags/hidden/COS_for_Win/Patch.rb) yourself.
