### ISSUE TITLE
adf patch

### ISSUE THREAD

**Issue by chrinide** [Z-H-Sun/CS_CCME_Posts#32]
Hi,

I have new version adf, if you would like to try patch, I will share.

**Comment by Z-H-Sun** [comment]
ADF has a really strong opinion on pirating their software. Especially, starting from the 2014 version, they will track you down if you attempt to change your system time to gain an additional trial period. One can easily get trapped by their intentionally prepared honeypot. So, I will not even consider cracking any version higher than 2012.
