### ISSUE TITLE
Can win version install on Mac by Whisky or Crossover ?

### ISSUE THREAD

**Issue by idolikechemistry** [Z-H-Sun/CS_CCME_Posts#34]
After the release of GPTK on Mac, there have recently been many solutions for translating and running Windows platform software on Mac. These include using software like Whisky or Crossover to create Windows containers for installing various applications or games. However, after setting up a Whisky container and following the usual installation process for the cracked version of Chem Draw you provided, I have been unable to install or use it successfully.

Could you provide some guidance on the installation process? Or is it the case that this cracked version of the software cannot be used in virtual containers?

Thank you for your help.

**Comment by Z-H-Sun** [comment]
I don't quite understand why you don't use Chem Draw for Mac. Its cracked version is provided in the same article.

I can't think of any context where something the Win version of Chem Draw can do while the Mac version can't. Maybe I'm wrong. But even it is true, you should ask Revvity / Whisky / etc., not me...
