### ISSUE TITLE
gaussview for mac有64位的资源吗

### ISSUE THREAD

**Issue by SSSSSimon** [Z-H-Sun/CS_CCME_Posts#4]
32位的gaussview5已经打不开了QAQ

**Comment by Z-H-Sun** [comment]
抱歉，当时连gaussview5也找了很久，最后还是别人给的。不支持32位是mac os的问题，已经有不少其他翻过车的案例了（比如某校Adobe的官方激活工具），这个真的是没办法（除了系统降级）→_→
