### ISSUE TITLE
Mac 可以同時安裝兩種版本的MestReNova嗎？

### ISSUE THREAD

**Issue by scout1256** [Z-H-Sun/CS_CCME_Posts#6]
目前安裝14.1.0-24037
想安裝14.2.0
保險起見想測試完14.2.0才刪除14.1.0

**Comment by Z-H-Sun** [comment]
I am not a Mac user, so chances are that what I say do not work. But here’s my understanding:

Theoretically yes. In the Application folder, rename the lower version MestReNova to another name as you like. Then install the latest version as you normally do.  These two versions won’t affect one another.

Note that the patch only deals with the package called “MestReNova,” so do not rename it before patching.
